// <auto-generated />
namespace taskman.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_support : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_support));
        
        string IMigrationMetadata.Id
        {
            get { return "201504150836579_user_support"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
